// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UrlShortener.API.Data;

#nullable disable

namespace UrlShortener.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("UrlShortener.API.Models.ShortenedUrl", b =>
            {
                b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<long>("ClickCount").HasColumnType("INTEGER");
                b.Property<string>("Code").IsRequired().HasMaxLength(10).HasColumnType("TEXT");
                b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                b.Property<DateTime?>("ExpiresAt").HasColumnType("TEXT");
                b.Property<bool>("IsActive").HasColumnType("INTEGER");
                b.Property<DateTime?>("LastAccessedAt").HasColumnType("TEXT");
                b.Property<string>("LastAccessedIp").HasColumnType("TEXT");
                b.Property<string>("OriginalUrl").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Title").HasColumnType("TEXT");
                b.HasKey("Id");
                b.HasIndex("Code").IsUnique();
                b.ToTable("ShortenedUrls");
            });
#pragma warning restore 612, 618
        }
    }
}
